#! /bin/sh

#Set default eth0
defautIface=eth0

#Kill all hostapd
sudo killall hostapd
sudo rfkill unblock wlan

#Run hostapd
sudo hostapd -B /etc/hostapd/hostapd.conf

#Set DHCP
ifconfig wlan0 192.168.201.1 netmask 255.255.255.0 up
#Restart DHCP server
sudo /etc/init.d/my restart

#Iptable rule
sudo sysctl -w net.ipv4.ipforward=1
sudo iptables -F
sudo iptables -X
sudo iptables -t nat -F
sudo iptables -t nat -X
sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
